name: Run Mobilewright

on:
  push:
    branches: ["*"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build .ipa for iOS real device
        run: |
          make ipa

      - name: Install mobilewright
        run: |
          npm install --no-save mobilewright@latest

      - name: Run tests using mobilewright
        env:
          MOBILECLI_TOKEN: ${{ secrets.MOBILEFLEET_API_KEY }}
        run: |
          npx -y @mobilenext/mobilecli fleet allocate --platform "ios" --version "18.6.2" --verbose --wait --timeout 600
          npx -y @mobilenext/mobilecli devices -v
          npx -y @mobilenext/mobilecli apps install ./build/Milliways-unsigned.ipa

      - name: Run tests using mobilewright
        env:
          MOBILECLI_TOKEN: ${{ secrets.MOBILEFLEET_API_KEY }}
        run: |
          # adding "|| true" because some of the tests are expected to fail
          npx mobilewright test --reporter='list,html' || true

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_SAMPLES_UPLOAD_ROLE_ARN }}
          aws-region: us-west-2

      - name: Upload samples to S3
        run: |
          GITSHA=$( git rev-parse HEAD )
          aws s3 cp --quiet --recursive --acl public-read mobilewright-report s3://mobilewright-samples/milliways/runs/$GITSHA
          echo "→ Report uploaded to https://mobilewright-samples.s3.amazonaws.com/milliways/runs/$GITSHA/index.html"

