name: Run Mobilewright

on:
  push:
    branches: ["*"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      
      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Build .ipa for iOS real device
        run: |
          # create an .ipa file for real iOS devices
          make ipa | xcbeautify

      - name: Run tests using mobilewright
        run: |
          # install mobilewright
          npm install --no-save mobilewright@latest

          # allocate devics
          export MOBILECLI_TOKEN="${{ secrets.MOBILEFLEET_API_KEY }}"
          npx -y @mobilenext/mobilecli fleet allocate --platform "ios" --name "Apple iPhone 16*" --version ">=18"
          npx -y @mobilenext/mobilecli devices -v      
          sleep 200
          npx mobilewright devices
          npx -y @mobilenext/mobilecli apps install ./build/Milliways-unsigned.ipa
          npx mobilewright test

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_SAMPLES_UPLOAD_ROLE_ARN }}
          aws-region: us-west-2

      - name: Upload samples to S3
        run: |
          GITSHA=$( git rev-parse HEAD )
          aws s3 cp --recursive --acl public-read mobilewright-report/ s3://mobilewright-samples/milliways/runs/$GITSHA

