name: Run Mobilewright

on:
  push:
    branches: ["*"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build .ipa for iOS real device
        run: |
          make ipa

      - name: Upload .ipa artifact
        uses: actions/upload-artifact@v5
        with:
          name: ipa-build
          path: build/Milliways-unsigned.ipa

  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      MOBILECLI_TOKEN: ${{ secrets.MOBILEFLEET_API_KEY }}
    steps:
      - uses: actions/checkout@v5

      - name: Download .ipa artifact
        uses: actions/download-artifact@v5
        with:
          name: ipa-build
          path: build

      - name: Allocate real iOS device
        run: |
          npx -y @mobilenext/mobilecli fleet allocate --platform "ios" --version "18.6.2" --verbose --wait --timeout 600
          npx -y @mobilenext/mobilecli devices -v
          npx -y @mobilenext/mobilecli apps install ./build/Milliways-unsigned.ipa

      - name: Run tests using mobilewright
        run: |
          # some of the tests are expected to fail, so we're adding || true
          cd tests
          npm install --ignore-scripts
          npm run test || true

      - name: Upload test report
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: mobilewright-report
          path: tests/mobilewright-report

  upload_test_results:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - uses: actions/checkout@v5

      - name: Download test report
        uses: actions/download-artifact@v5
        with:
          name: mobilewright-report
          path: tests/mobilewright-report

      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_SAMPLES_UPLOAD_ROLE_ARN }}
          aws-region: us-west-2

      - name: Upload samples to S3
        run: |
          GITSHA=$( git rev-parse HEAD )
          aws s3 cp --quiet --recursive --acl public-read tests/mobilewright-report s3://mobilewright-samples/milliways/runs/$GITSHA
          echo "→ Report uploaded to https://mobilewright-samples.s3.amazonaws.com/milliways/runs/$GITSHA/index.html"
